### ISSUE TITLE
tags not imported correctly

### ISSUE THREAD

**Issue by voigt** [jpadilla/tumblr-to-ghost#18]
Scenario:

```
Tumblr entry #1 has tags:
#a, #b, #c

Tumblr entry #2 has tags:
#a, #b, #d
```

After exporting posts are created with following tags:

```
Ghost post #1 has tags:
#c

Ghost post #2 has tags:
#a, #b, #d
```

=> Every tag is only assgined to a single post.

This leads to following tag overview:

![current](https://raw.githubusercontent.com/voigt/tumblr-to-ghost/images/images/issue_18_old.JPG)

This is how this certain overview should look like (with a correct tag assignment):
![should be](https://raw.githubusercontent.com/voigt/tumblr-to-ghost/images/images/issue_18_new.JPG)

**Comment by jpadilla** [comment]
This should have been fixed by #18. @voigt thanks! latest should be deployed already at https://tumblr-to-ghost.herokuapp.com/
