### ISSUE TITLE
[Bug] *.json file not importable when duplicate titles in tumblr src

### ISSUE THREAD

**Issue by voigt** [jpadilla/tumblr-to-ghost#20]
When the tumblr post has multiple posts with title "abc" the export files will generate the same amount of posts - unfortunately do all have the same slug. Ghost will refuse to import *.json files wich contain multiple posts with an identical slug.

**Quick fix:**
In line [116](https://github.com/jpadilla/tumblr-to-ghost/blob/master/tumblr_to_ghost.py#L116) assign e.g. the timestamp:

```
[...]
                'title': title,
                'slug': slug + str(timestamp),
                'markdown': body,
                'html': body,
[...]
```

**Better fix:**
a) Create the first slug as before. Increment every next slug.

```
#1 Post title = "Hello"
slug = "Hello"

#1 Post title = "Hello"
slug = "Hello-2"

#1 Post title = "Hello"
slug = "Hello-3"
[...]
```

b) Create the first slug as before. Add timestamp to every next slug.

```
#1 Post title = "Hello"
slug = "Hello"

#1 Post title = "Hello"
slug = "Hello-2015-05-01"

#1 Post title = "Hello"
slug = "Hello-2015-05-04"
[...]
```

The decision is up to you @jpadilla :)

**Comment by jpadilla** [comment]
@voigt definitely option a seems the way to go.
